version: '3'

services:
  php:
    build: .docker/php
    tty: true
    depends_on:
      - mysql
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html:delegated
  mysql:
    image: mysql:8
    ports:
      - 3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: enable
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_DATABASE: laravel
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
